#!/usr/bin/env node
/**
 * Projects skills onto Codex and Cursor (ADR-0004).
 *
 * Scope is deliberately narrow: SKILL.md only. That format is byte-identical across all
 * three tools, so this script copies files and writes an installer — there is no
 * translation step and therefore nothing that can silently produce a wrong artifact.
 *
 * Commands, CLAUDE.md rules, hooks, MCP config, and packs are NOT projected. Each of
 * those needs a real per-tool transformation, which is where the fragility lives, and
 * none of them is common enough in the catalog to earn that cost yet. See ADR-0004.
 *
 * Output goes to dist/, committed so a target installs by `git clone` with nothing to run.
 *
 * Run with --check to fail instead of writing when the committed dist/ is stale. CI uses
 * that mode: without it, editing a SKILL.md body and forgetting to run this script leaves
 * Codex and Cursor serving the previous version with a green build.
 */

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, sep } from "node:path";
import { ROOT, isExternal, loadCatalog, loadConfig } from "./lib/catalog.mjs";

const CHECK = process.argv.includes("--check");

const TARGETS = {
  codex: { skillsDir: "codex/skills", installTo: "$HOME/.agents/skills", from: "skills" },
  cursor: {
    skillsDir: "cursor/.cursor/skills",
    installTo: "$HOME/.cursor/skills",
    from: ".cursor/skills",
  },
};

const config = await loadConfig();
const catalog = await loadCatalog(config);

const DIST = join(ROOT, "dist");

/** Path inside dist/ -> file contents. Built in memory so --check never touches the tree. */
const planned = new Map();
const counts = { codex: 0, cursor: 0 };

/** Every file under `dir`, as paths relative to it. Skills may ship references/ and scripts. */
async function filesUnder(dir, prefix = "") {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await filesUnder(join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

for (const entry of catalog) {
  if (entry.kind === "pack") continue; // packs are a Claude Code feature (ADR-0005)
  if (isExternal(entry)) continue; // content is not in this repository (I2)

  const skillsRoot = join(ROOT, config.pluginsRoot, entry.name, "skills");
  if (!existsSync(skillsRoot)) continue;

  const skills = (await readdir(skillsRoot, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const [tool, target] of Object.entries(TARGETS)) {
    if (!(entry.tools ?? []).includes(tool)) continue;
    for (const skill of skills) {
      for (const file of await filesUnder(join(skillsRoot, skill))) {
        planned.set(
          `${target.skillsDir}/${skill}/${file}`,
          await readFile(join(skillsRoot, skill, file)),
        );
      }
      counts[tool] += 1;
    }
  }
}

// Symlink rather than copy: Codex follows symlinked skill folders, so `git pull` in the
// clone updates every installed skill in place with no second step (ADR-0004).
const installer = (target) => `#!/usr/bin/env bash
# Generated by scripts/build-targets.mjs. Do not edit.
set -euo pipefail

SRC="$(cd "$(dirname "\${BASH_SOURCE[0]}")/${target.from}" && pwd)"
DEST="\${1:-${target.installTo}}"

mkdir -p "$DEST"
for skill in "$SRC"/*/; do
  name="$(basename "$skill")"
  rm -rf "\${DEST:?}/$name"
  ln -s "$skill" "$DEST/$name"
  echo "linked $name -> $DEST/$name"
done

echo
echo "Done. Skills are symlinked, so 'git pull' in this repository updates them in place."
`;

for (const [tool, target] of Object.entries(TARGETS)) {
  if (!counts[tool]) continue;
  planned.set(`${tool}/install.sh`, Buffer.from(installer(target)));
}

if (CHECK) {
  const onDisk = existsSync(DIST)
    ? new Set((await filesUnder(DIST)).map((f) => f.split(sep).join("/")))
    : new Set();

  const stale = [];
  for (const [rel, content] of planned) {
    if (!onDisk.has(rel)) {
      stale.push(`missing  dist/${rel}`);
      continue;
    }
    const current = await readFile(join(DIST, rel));
    if (!current.equals(content)) stale.push(`differs  dist/${rel}`);
  }
  for (const rel of onDisk) {
    if (!planned.has(rel)) stale.push(`orphan   dist/${rel}`);
  }

  if (stale.length) {
    console.error(
      `dist/ is out of date:\n${stale.map((s) => `  - ${s}`).join("\n")}\n\n` +
        `Run \`node scripts/build-targets.mjs\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`dist/ is up to date (${planned.size} file(s)).`);
} else {
  await rm(DIST, { recursive: true, force: true });
  for (const [rel, content] of planned) {
    const abs = join(DIST, rel);
    await mkdir(join(abs, ".."), { recursive: true });
    await writeFile(abs, content, rel.endsWith("install.sh") ? { mode: 0o755 } : undefined);
  }
  console.log(
    `Projected ${counts.codex} skill(s) to dist/codex and ${counts.cursor} to dist/cursor.`,
  );
}
