#!/usr/bin/env node
/**
 * Projects skills onto Codex and Cursor (ADR-0004).
 *
 * Scope is deliberately narrow: SKILL.md only. That format is byte-identical across all
 * three tools, so this script copies files and writes an installer — there is no
 * translation step and therefore nothing that can silently produce a wrong artifact.
 *
 * Commands, CLAUDE.md rules, hooks, MCP config, and packs are NOT projected. Each of
 * those needs a real per-tool transformation, which is where the fragility lives, and
 * none of them is common enough in the catalog to earn that cost yet. See ADR-0004.
 *
 * Output goes to dist/, committed so a target installs by `git clone` with nothing to run.
 */

import { cp, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { ROOT, loadCatalog, loadConfig } from "./lib/catalog.mjs";

const TARGETS = {
  codex: { skillsDir: "codex/skills", installTo: "$HOME/.agents/skills", from: "skills" },
  cursor: {
    skillsDir: "cursor/.cursor/skills",
    installTo: "$HOME/.cursor/skills",
    from: ".cursor/skills",
  },
};

const config = await loadConfig();
const catalog = await loadCatalog(config);

const DIST = join(ROOT, "dist");
await rm(DIST, { recursive: true, force: true });

const counts = { codex: 0, cursor: 0 };

for (const entry of catalog) {
  if (entry.kind === "pack") continue; // packs are a Claude Code feature (ADR-0005)

  const skillsRoot = join(ROOT, config.pluginsRoot, entry.name, "skills");
  if (!existsSync(skillsRoot)) continue;

  const skills = (await readdir(skillsRoot, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const [tool, target] of Object.entries(TARGETS)) {
    if (!(entry.tools ?? []).includes(tool)) continue;
    for (const skill of skills) {
      const dest = join(DIST, target.skillsDir, skill);
      await mkdir(join(DIST, target.skillsDir), { recursive: true });
      await cp(join(skillsRoot, skill), dest, { recursive: true });
      counts[tool] += 1;
    }
  }
}

// Symlink rather than copy: Codex follows symlinked skill folders, so `git pull` in the
// clone updates every installed skill in place with no second step (ADR-0004).
const installer = (target) => `#!/usr/bin/env bash
# Generated by scripts/build-targets.mjs. Do not edit.
set -euo pipefail

SRC="$(cd "$(dirname "\${BASH_SOURCE[0]}")/${target.from}" && pwd)"
DEST="\${1:-${target.installTo}}"

mkdir -p "$DEST"
for skill in "$SRC"/*/; do
  name="$(basename "$skill")"
  rm -rf "\${DEST:?}/$name"
  ln -s "$skill" "$DEST/$name"
  echo "linked $name -> $DEST/$name"
done

echo
echo "Done. Skills are symlinked, so 'git pull' in this repository updates them in place."
`;

for (const [tool, target] of Object.entries(TARGETS)) {
  if (!counts[tool]) continue;
  await writeFile(join(DIST, tool, "install.sh"), installer(target), { mode: 0o755 });
}

console.log(
  `Projected ${counts.codex} skill(s) to dist/codex and ${counts.cursor} to dist/cursor.`,
);
